### ISSUE TITLE
docker_container does not integrate with runit

### ISSUE THREAD

**Issue by dysinger** [bflad/chef-docker#135]
tim@ip-10-86-246-182:~$ sudo docker ps
    CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                  NAMES
    c445ba9b8ace        registry:0.6.7      /bin/sh -c 'cd /dock   15 hours ago        Up 12 seconds       0.0.0.0:80->5000/tcp   registry
    tim@ip-10-86-246-182:~$ sudo docker kill c445ba9b8ace
    c445ba9b8ace
    tim@ip-10-86-246-182:~$ sudo docker ps
    CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                  NAMES
    c445ba9b8ace        registry:0.6.7      /bin/sh -c 'cd /dock   15 hours ago        Up 1 seconds        0.0.0.0:80->5000/tcp   registry
    tim@ip-10-86-246-182:~$ sudo docker kill c445ba9b8ace
    c445ba9b8ace
    tim@ip-10-86-246-182:~$ sudo docker ps
    CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                  NAMES
    c445ba9b8ace        registry:0.6.7      /bin/sh -c 'cd /dock   15 hours ago        Up 2 seconds        0.0.0.0:80->5000/tcp   registry
    tim@ip-10-86-246-182:~$ sudo sv status registry
    down: registry: 0s, normally up, want up; run: log: (pid 966) 57211s

**Comment by someara** [comment]
init_type has been removed on the docker_container resource
