### ISSUE TITLE
When specifying node[:docker][:host], docker doesn't seem to restart & pickup attributes

### ISSUE THREAD

**Issue by adnichols** [bflad/chef-docker#140]
I see that there are notifies on the template for /etc/default/docker however when I specify the attribute such as:
```
node.override[:docker][:host] = [ 'tcp://0.0.0.0:4243' ]
```
On a newly provisioned system where docker is installed in the same converge as this configuration is applied it doesn't seem to restart docker after making this change to the config. If I manually restart docker after the converge I see these options picked up. 

Opening this issue for tracking - I may be able to dig into this more and open a PR but can't right now. 

Platform is Ubuntu 14.04 w/ Chef 11.12.2

**Comment by someara** [comment]
Attributes API is being deprecated as of 0.40.x
