### ISSUE TITLE
Docker deamon not really started on EL6

### ISSUE THREAD

**Issue by dpetzel** [bflad/chef-docker#162]
After adding the service test in https://github.com/bflad/chef-docker/pull/161, I found the service check fails. The interesting part is that service status reports a running PID, but attempting to list images fails. Manually restarting the service seems to clear things up.

It seems the recipe may need to issue one more restart somewhere along the line?

Here is the output showing what I'm seeing on both RHEL6.5 and Centos 6.4:
````
[root@host ~]# service docker status
docker (pid  1630) is running...
[root@host ~]# docker images
2014/06/04 03:58:07 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@host ~]# service docker restart
Stopping docker:                                           [  OK  ]
Starting docker:	                                   [  OK  ]
[root@host ~]# service docker status
docker (pid  1873) is running...
[root@host ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
````

**Comment by someara** [comment]
Should work as of 0.40.x
