### ISSUE TITLE
Add option to change current directory and use sudo in docker_image

### ISSUE THREAD

**Issue by amjibaly** [bflad/chef-docker#163]
Here's a link to the change I had to make in the image provider to get docker_image to work in OpsWorks:

https://github.com/amjibaly/chef-docker/commit/b2e5e19f01683d95a1170a64d94b7697a47bb43c

I also had to make the following change in helpers.rb:

https://github.com/amjibaly/chef-docker/commit/a75416b1e1c14b576a5922318c6ca7c0b48b75f6

**Comment by someara** [comment]
Garbage collecting this issue... feel free to re-open if this is still a thing.
