### ISSUE TITLE
upstart: docker started event fires before `/var/run/docker.sock` exists

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#174]
As a workaround for dotcloud/docker#6647 I am now forcing `default['docker']['bind_socket'] = 'unix:///var/run/docker.sock'` in my wrapper cookbook, even if the `bind_socket` attribute is now deprecated and will be removed soon.

To explain the issue quickly, upstart scripts that `start on started docker` may fail because in some cases (usually after rebooting the host) docker (the daemon) does not create the `/var/run/docker.sock` fast enough; the consequence is that the container services or anything that invokes `docker start` or other docker (client) commands will fail until the socket is actually up.

**Comment by someara** [comment]
Should work as of 0.40.x
