### ISSUE TITLE
Container remove_volume action is broken by design

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#182]
Opening this issue because after fixing #181 I noticed that the `remove_volume` action of the docker_container resource is broken in a similar way than links, but unlike the remove_link action it cannot be fixed without changing the documented API, I'd rather have you fix it than me :-)

# The problem

The remove_volume action is documented [here](https://github.com/bflad/chef-docker#docker_container-action-remove_volume). It is supposed to remove some volumes (possibly not all) that were exported by a container while that container is being removed.

However, there is (as of 1.0.1) no version of `docker rm` with such a feature. According to `man docker-rm` there is a `--volumes` flag that when set to true will remove all volumes exported by the container while removing that container.

# Possible solution

We should remove the `remove_volume` action of the docker_container resource, and replace it with a `--volumes` cli flag that would go docker_container action remove, like current the `--force` cli flag.

**Comment by someara** [comment]
garbage collecting this issue since it seems invalid with modern versions.
re-open if its still a problem
