### ISSUE TITLE
notifies :redeploy fails, but manually notifying :stop, :remove and :run works

### ISSUE THREAD

**Issue by rdsubhas** [bflad/chef-docker#198]
Reference: https://snap-ci.com/rapidftr/RapidFTR/branch/master/logs/defaultPipeline/74/DEV?back_to=build_history

    notifies :redeploy, ..., :immediately

Fails randomly. Instead we have switched to:

    notifies :stop, ..., :immediately
    notifies :remove, ..., :immediately
    notifies :run, ..., :immediately

And that works ~~consistently well~~ better. Any ideas what could be the issue?

EDIT: That doesn't work consistently well, it just works "better", and does fail occasionally.

**Comment by caleb** [comment]
This is my experience as well. When using `:redeploy` I get an error about not being able to remove an running container. As a fix I'm using `action [:stop, :remove, :run]`.

**Comment by someara** [comment]
FIxed in master
