### ISSUE TITLE
no version specified 

### ISSUE THREAD

**Issue by ghost** [bflad/chef-docker#207]
The README.md seemed to indicate it would install the latest if no verison specified. 

Recipe: docker::package
  * apt_repository[docker] action add
    * remote_file[/var/chef/cache/gpg] action create (up to date)
    * execute[install-key gpg] action run (skipped due to not_if)
    * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * execute[apt-get update] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/docker.list] action create (up to date)
     (up to date)
  * package[lxc-docker] action install
    * No version specified, and no candidate version available for lxc-docker
    ================================================================================
    Error executing action `install` on resource 'package[lxc-docker]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for lxc-docker
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/docker/recipes/package.rb
    
     29:   package p do
     30:     options '--force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
     31:     action node['docker']['package']['action'].intern
     32:   end
     33: when 'mac_os_x', 'mac_os_x_server'
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/docker/recipes/package.rb:29:in `from_file'
    
    package("lxc-docker") do
      action [:install]
      retries 0
      retry_delay 2
      guard_interpreter :default
      options "--force-yes -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confold\""
      package_name "lxc-docker"
      timeout 900
      cookbook_name "docker"
      recipe_name "package"
    end
    

Running handlers:
[2014-09-04T03:13:07-05:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-04T03:13:07-05:00] ERROR: Exception handlers complete
[2014-09-04T03:13:07-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 73.608711214 seconds
[2014-09-04T03:13:07-05:00] ERROR: package[lxc-docker] (docker::package line 29) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for lxc-docker
[2014-09-04T03:13:08-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
root@52-54-0-a9-a9-10:/home/ubuntu#

**Comment by hd-deman** [comment]
same for me under ubuntu14.04

**Comment by hd-deman** [comment]
fixed for me by running
```ruby
package 'apt-transport-https' do
  action :install
end

execute 'apt-get update'
```

after `apt_repository 'docker'` resource.

**Comment by someara** [comment]
Packages deprecated as of 0.40.x
