### ISSUE TITLE
Any chance HTTPS_PROXY can be added for us corporate shills?

### ISSUE THREAD

**Issue by chrisfarnham** [bflad/chef-docker#222]
Same as this issue: https://github.com/bflad/chef-docker/pull/1 

Thank you!

**Comment by rochacon** [comment]
Docker [uses](https://github.com/docker/docker/search?q=ProxyFromEnvironment&type=Code&utf8=%E2%9C%93) [`http.ProxyFromEnvironment`](http://golang.org/pkg/net/http/#ProxyFromEnvironment) from the Go std library to resolve proxy configuration. This helper function [will honor](http://golang.org/src/net/http/transport.go?s=4805:4862#L120) `HTTPS_PROXY` env var.

I also need this setting, should place a PR soon.

**Comment by someara** [comment]
Should work via docker_service as of 0.40.x
