### ISSUE TITLE
docker_image action :pull seems always up to date

### ISSUE THREAD

**Issue by alamut** [bflad/chef-docker#241]
Sample code from the wrapper cookbook:
```
docker_image 'dockerfile/redis' do
  tag 'latest'
  action :pull
end
```

The image will be downloaded correctly, but notifying other resources is quite difficult while the `docker_image` resource is always up to date:
```
Recipe: int-docker-registry::default
  * docker_image[dockerfile/redis] action pull
  (up to date)
  (up to date)
```

Case details:
- AWS with kitchen-ec2
- Ubuntu 14.04
- no local `dockerfile/redis` image present before running chef

**Comment by someara** [comment]
This is expected behavior for :pull. :pull_if_missing is the droid you're looking for.

**Comment by alamut** [comment]
**someara**, the expected behaviour for `pull_if_missing` is to pull the image if it does not exist, and do not update the content despite the changes in the registry.
the expected for `pull` is to check if the local image differs from the remote, and update it if needed, or throw `up to date` in the other case.

am i saying some kind of nonsense?

**Comment by someara** [comment]
Sorry... was on an issue closing tear. You're probably right. I'll investigate the pull api results for a result

**Comment by someara** [comment]
This should behave properly now in 1.0.5. Enjoy!
