### ISSUE TITLE
iptables cookbook can clobber things

### ISSUE THREAD

**Issue by coderanger** [bflad/chef-docker#249]
You are pulling in the iptables cookbook for binary installs because docker wants iptables. Unfortunately the default ipptables recipe both installs it and then takes over the system's iptables config. If you are using one of the other firewall config cookbooks, this can easily leave you in a bad place. At a minimum it would be nice if you could disable this include_recipe, or better would be to only install iptables and not try to configure it.

**Comment by amaltson** [comment]
:+1:, I just had a ssh blocked on a system after running this cookbook :sob:

**Comment by bflad** [comment]
Yikes. Sorry you're running into this. How would you prefer to handle? I'd hate to manually install it, especially because there's differing package names between platforms and versions.

I'd prefer an upstream fix to provide an "install" recipe here personally (then we'd just call that):
https://supermarket.chef.io/cookbooks/iptables

Thoughts?

**Comment by amaltson** [comment]
In my fork I changed it to include the `disabled` recipe instead of the default recipe and that worked fine. Obviously this will make others unhappy because it'll disable iptables, but we're not even using it right now.

**Comment by cmluciano** [comment]
It appears that the new iptables cookbook version simply installs and drops a file to allow rebuilding. https://github.com/opscode-cookbooks/iptables/blob/master/recipes/default.rb

**Comment by bflad** [comment]
@cmluciano that's excellent news!

Does anyone have any strong feelings about what we should do in the docker cookbook? I really prefer to lean on using other specialized community cookbooks to provide ways to "do the right thing" as well as be properly maintained/updated.

**Comment by someara** [comment]
Iptables is out of scoke for the Docker cookbook as of 0.40.x

**Comment by amaltson** [comment]
@someara ah so it was removed, thanks!
