### ISSUE TITLE
Presence of ::Dir.home breaks chef-client when run as daemon

### ISSUE THREAD

**Issue by redfive** [bflad/chef-docker#252]
When running chef as a daemon via /etc/init.d the $HOME env var doesn't get set and therefore the usage of ::Dir.home fails.

Problem line is:
https://github.com/bflad/chef-docker/blob/master/libraries/helpers.rb#L164

**Comment by gavinheavyside** [comment]
I hit this too, and I've hacked a dirty workaround at https://github.com/gavinheavyside/chef-docker/tree/run-as-service-with-private-registry. It's working for me running chef-client as a runit service, but I don't think it's very portable or robust so I'm not going to open a PR as-is.

**Comment by bflad** [comment]
Hi @redfive and @gavinheavyside - have you discovered anything else with this? There's also #261 which might introduce more usage of `::Dir.home` so would be curious with your experiences. Thanks!

**Comment by gavinheavyside** [comment]
Hi @bflad, sorry, nothing to add so far. I'm using a fork with a workaround for now. As we start to push more stuff into production I hope to revisit, it will probably be May before I get chance though. AFAIK using `::Dir.home` is likely to cause issues with chef-client running as a service, as there is no login shell and variables like $HOME aren't set. See opscode-cookbooks/chef-client#226

**Comment by someara** [comment]
This should be fixed up as of 0.40.x
