### ISSUE TITLE
Port mappings are lost during sockets determination for systemd

### ISSUE THREAD

**Issue by gosuri** [bflad/chef-docker#256]
Port mappings are lost during sockets determination for systemd. For example:
```
docker_container "container" do
  action :run
  port "8080:1234"
  detach true
end
```
will run container with `--publish 1234` instead of `--publish 8080:1234`

This is due to `gsub!` in https://github.com/bflad/chef-docker/blob/master/providers/container.rb#L627

**Comment by bflad** [comment]
Same note as #253 -- please feel free to reopen if you're having trouble after 0.37.0. Thanks!
