### ISSUE TITLE
Allow docker_registry to login for another account than root

### ISSUE THREAD

**Issue by patatepartie** [bflad/chef-docker#261]
When using `docker_registry` the `docker login` command is run as `root`. 
This is the expected behaviour when interacting with `docker` only through `chef`, but it doesn't allow another user of the provisioned node to interact with a registry.

The workaround is simple - copy the `/root/.dockercfg` to `$HOME/.dockercfg` - but it would be cleaner to allow a `user` parameter to the `docker_registry` resource.

**Comment by omribahumi** [comment]
+1

This would also require having a `user` attribute for all LWRPs.
I suggest having a node attribute for the default docker user.

**Comment by someara** [comment]
This has been reimplemented to talk directly to the API
