### ISSUE TITLE
Missing device-mapper-libs causes docker daemon to crash

### ISSUE THREAD

**Issue by routelastresort** [bflad/chef-docker#271]
CentOS 6.x-only

Fixed with `sudo yum install device-mapper-libs`.  I'll look into what's happening now (constant freezes), but maybe CentOS 7.x is the only sane answer anyway.

Docker wouldn't start, and was failing Test Kitchen tests.
```
[vagrant@default-centos-65 ~]$ sudo service docker start
                                                           [FAILED]
/var/run/docker.pid still exists...
[vagrant@default-centos-65 ~]$ sudo rm -rf /var/run/docker.pid 
[vagrant@default-centos-65 ~]$ sudo service docker start
Starting docker:	                                   [  OK  ]
```

/var/log/docker:
```
time="2015-03-06T09:30:19Z" level="info" msg="WARNING: You are running linux kernel version 2.6.32-431.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.8.0." 
time="2015-03-06T09:30:19Z" level="info" msg="Listening for HTTP on unix (/var/run/docker.sock)" 
/usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference
```

Referenced in https://github.com/netdevops/netdevops-cookbook/issues/13

**Comment by routelastresort** [comment]
Also, I had better luck with `sudo yum install libvirt libvirt-client python-virtinst` to get LXC v.s. whatever the LXC cookbook was doing.  I'm not sure if this was before or after my cookbook was fixed (had to destroy and start over).

**Comment by bflad** [comment]
@routelastresort did you find out anything else or want me to look deeper into this? Much appreciated.

**Comment by someara** [comment]
Out of scope for the Docker cookbook as of 0.40.x. Configuration of cgroups and backend storage should be handled in another cookbook
