### ISSUE TITLE
Centos 7 Systemd network settings

### ISSUE THREAD

**Issue by mdbishop** [bflad/chef-docker#273]
On Centos7 (perhaps other SystemD based distros, just moving over from Debian), the recipe writes out to /etc/sysconfig/docker DOCKER_OPTS as expected.  However systemd ignores any network related parameters unless contained in a separate docker-network file.

So, the following in /etc/sysconfig/docker refuses to pick up the network directives:
```
DOCKER_OPTS=' --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock --graph=/local/docker --restart=false --storage-driver=btrfs'
```

After adding the following to /etc/sysconfig/docker-network all works as expected:
```
DOCKER_NETWORK_OPTIONS=  --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock
```

**Comment by bflad** [comment]
As mentioned in #272, I'm curious how you wound up needing these. I think some of the platform detection in the upcoming 0.37.0 might help as `/etc/sysconfig/docker*` isn't used in this cookbook's systemd support. Please let me know if you've discovered more in the last month. Thanks!

**Comment by someara** [comment]
This should be fixed up with the docker_service resource as of 0.40.x
