### ISSUE TITLE
Centos 7 Systemd TMPDIR directive

### ISSUE THREAD

**Issue by mdbishop** [bflad/chef-docker#274]
When adding a custom TMPDIR, the recipe writes this out to /etc/sysconfig/docker as

```
export TMPDIR=xxx
```
Docker logs the following:
```
Mar  7 01:22:09 london systemd: Ignoring invalid environment 'export TMPDIR=/local/tmp/docker/': /etc/sysconfig/docker
```

Manually changing this to:

```
TMPDIR=xxx
```

works as expected.

**Comment by bflad** [comment]
Same note as #272 and #273 - I bet the missing systemd detection that is in 0.37.0 will help here, but please let me know if I'm offbase. Thanks!

**Comment by someara** [comment]
This should be fixed up with the docker_service resource as of 0.40.x
