### ISSUE TITLE
Remove daemon_options restart option

### ISSUE THREAD

**Issue by rudijs** [bflad/chef-docker#275]
Hi,

Should the *restart* option from the *daemon_options* be removed altogether?

Line 93 in /libraries/helpers.rb

For me on Ubuntu 14.04 by default this cookbook installed docker version 1.5 so out of the box I can use restart policies on the container run command.

For the container restart policies to work properly I had to manually remove the *--restart=false* from */etc/default/docker*

    DOCKER_OPTS=' --host=unix:///var/run/docker.sock --restart=false'

From my readings the new restart policies from docker version 1.2 are more reliable than the daemon restart option.

Thanks.

**Comment by bflad** [comment]
From what I've seen, I'd agree with you! Should we default the restart attribute to `nil` instead of `false` as a bugfix until we remove it in 1.0 of the cookbook?

**Comment by rudijs** [comment]
Ah .. I hadn't tried, or even thought of, using a nil value.

Yeah, that works fine for me here now, I set it in my wrapper cookbook attributes/default.rb like so:

    default['docker']['restart'] = nil
    default['docker']['options'] = "--insecure-registry #{node["network"]["interfaces"]["eth1"]["addresses"].keys[1]}:5000"

So that prevents any --restart in the /etc/default/docker file, which is just what I need.

I think with Docker 1.5 being installed by default, it would benefit other users if nil was the default.

Then, as you suggest complete removal altogether later on.

Cheers.

**Comment by bflad** [comment]
Sounds great. Thank you very much for testing the workaround. This will make the cut into 0.37.0.
