### ISSUE TITLE
Use --ip-forward instead of sysctl for docker 1.4.1

### ISSUE THREAD

**Issue by docwhat** [bflad/chef-docker#277]
If we're using docker version 1.4.1 or newer then we shouldn't use `sysctl` to turn on `ip-forward` but instead use the `docker --ip-forward=(true|false)` flag instead.

**Comment by bflad** [comment]
How detrimental is using `sysctl` on the newer versions? New flags will surely make things cleaner. Will take a look after 0.37.0 release. Thanks!

**Comment by docwhat** [comment]
It's an ordering thing:

1. System boots.
2. Docker runs, turning on ip-forwarding.
3. 30 minutes later, chef runs, turning off ip-forwarding.

So there is a pretty big window while the system will forward *any* packets.

If you *really* want to use sysctl, then you should use the `/etc/sysctl.conf` file to turn off ip-forwarding, except that without the `--ip-forward=false` flag to docker, it'll turn it back on.

I think the best approach is to pass it to docker and *not* try to add extra features to docker (e.g. don't support turning on/off ip-forwarding for docker < 1.4.1).  Especially security related items.

**Comment by someara** [comment]
This is out of scope for the Docker cookbook as of 0.40.x.
