### ISSUE TITLE
Release 0.37.0

### ISSUE THREAD

**Issue by bflad** [bflad/chef-docker#283]
I believe @tduffield has some changes so holding off on releasing 0.37.0 myself. All my changes are currently merged into master.

**Comment by tduffield** [comment]
Nope. You are good to go!

**Comment by bflad** [comment]
I just need to update the CHANGELOG from all the merges back in November. I'll get this sometime later today.

**Comment by docwhat** [comment]
W00T! I was about to suggest this because I need the `restart` flag on containers and the fix for the `:redeploy` action.

**Comment by rtrauntvein** [comment]
+1

**Comment by jperville** [comment]
Being late to the party but congratulations everyone!
