### ISSUE TITLE
Is there a possibility to access original docker_container resource from custom init_template ?

### ISSUE THREAD

**Issue by alex-fedorov** [bflad/chef-docker#286]
When using this:

```ruby
docker_container "name" do
  image "the_image"
  cookbook "my_cookbook"
  init_template "custom_init.conf.erb"
end
```

And in `custom_init.conf.erb` I want to be able to use `@current_resource` or something along these lines, which will enable me to access resource attributes, such as `link` for example.

**Comment by alex-fedorov** [comment]
I have this quick hack here: https://github.com/wimdu/chef-docker/compare/v0.36.0...wimdu:v0.36.0/allow_access_to_current_resource_from_custom_init_template#diff-114269aba847baa709d6a08687ffc745

**Comment by bflad** [comment]
Interesting use case. I'd be curious to see what you're doing in your custom init scripts. :)

If you submit this as a PR, I'll take a deeper look. Thanks!

**Comment by alex-fedorov** [comment]
Use case is to specify linked containers as a dependency of initial script,
so they will be run in proper order on boot. Otherwise some of them may
fail to start..

**Comment by someara** [comment]
init_template has been removed with the docker_container reimplementation in master
