### ISSUE TITLE
CoreOS support?

### ISSUE THREAD

**Issue by flaccid** [bflad/chef-docker#312]
Curious about this topic. Just wondering if there is any reason why it couldn't be achieved as I don't see a mention of it in the cookbook?
If its something that simply hasn't be added yet, we can all work on it :)

**Comment by bflad** [comment]
Hi could you explain a little more about your use case? I personally haven't seen anyone asking for it and CoreOS is not an "officially supported" Chef client platform. 

Please see these for details upstream about this topic:
* https://github.com/chef/chef/issues/1735
* https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md

**Comment by flaccid** [comment]
@bflad appreciate those links and your response. I think that explains it all.
I probably don't have a 'practical' use case in hindsight, it just seems like it would be awesome and means you wouldn't have to do anything manual such as commands if you choose to do CoreOS as your container host.
I guess its probably a better idea to bootstrap/manage your CoreOS host with something other than chef if you choose that over chef solutions such as this cookbook (which now I think I will simply use with ubuntu).
Thanks again!

**Comment by someara** [comment]
Garbage collecting due to inactionability... feel free to re-open if you think it was closed in error

**Comment by flaccid** [comment]
That's right, I was getting a bit too excited. cloud-init is generally what is used on CoreOS.
