### ISSUE TITLE
Image tag issue

### ISSUE THREAD

**Issue by klettier** [bflad/chef-docker#320]
Hello,

I'm attempting to specify a tag for 'elasticsearch' docker image with a specific version '1.5.2' but after running the cookbook I noticed that two versions of Elasticsearch were installed, one with the version I provided and one with the latest version.

![image](https://cloud.githubusercontent.com/assets/3425823/7880935/6a362108-05fe-11e5-96d0-96ec90d4a619.png)

## default.rb file

![image](https://cloud.githubusercontent.com/assets/3425823/7880955/a83cb75a-05fe-11e5-817d-27f0f093a310.png)

What can I do to get only the version of Elasticsearch I specified ?

**Comment by rtrauntvein** [comment]
Have you tried putting a `tag` attribute in your `docker_container` resource? 

i.e.:

```
docker_continer 'elasticsearch' do
  detach true
   tag '1.5.2'
end
```

**Comment by klettier** [comment]
I tried two ways :

## 1)
```

docker_image 'elasticsearch' do
end

docker_container 'elasticsearch' do
  detach true
   tag '1.5.2'
 end
```
After executing the cookbook I only got one elasticsearch with **the latest tag**

REPOSITORY    |      TAG        |         IMAGE ID      |      CREATED      |       VIRTUAL SIZE
---------------------|---------------- |-------------------------|---------------------|---------------------
elasticsearch   |    latest     |         35f93b783f17   |     4 days ago    |      514.1 MB

## 2)
```
docker_image 'elasticsearch' do
  tag '1.5.2'
end

docker_container 'elasticsearch' do
  detach true
   tag '1.5.2'
 end

```
After executing the cookbook I got two elasticsearch with **latest** and **1.5.2** tags

REPOSITORY    |      TAG        |         IMAGE ID      |      CREATED      |       VIRTUAL SIZE
---------------------|---------------- |-------------------------|---------------------|---------------------
elasticsearch   |    latest     |         35f93b783f17   |     4 days ago    |      514.1 MB
elasticsearch   |    1.5.2     |         65f15g841f78   |     4 days ago    |      514.5 MB

**I did many tests and docker always start the elasticsearch with the latest tag.**

**Comment by rtrauntvein** [comment]
I have a few recipes running that are setup like this:

```ruby
docker_image 'elasticsearch' do
  tag '1.5.2'
end

docker_container 'elasticsearch:1.5.2' do
  detach true
end
```

This runs the tagged version for me.

Maybe there is an issue with tag in the `docker_container ` resource?

**Comment by klettier** [comment]
With your recipe I got an error :

```
STDERR: time="2015-06-03T07:24:46Z" level=fatal msg="Error response from daemon: Invalid container name (elasticsearch:1.5.2), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed"
---- End output of docker run  --detach=true --name="elasticsearch:1.5.2" elasticsearch:1.5.2  ----
Ran docker run  --detach=true --name="elasticsearch:1.5.2" elasticsearch:1.5.2  returned 1
[2015-06-03T07:24:47+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
My host is an Ubuntu 12.04 and chef package is in version 12.3.0

**Comment by rtrauntvein** [comment]
Ah we may have to set a different name:

```ruby
docker_container 'elasticsearch:1.5.2' do
  detach true
  name 'elasticsearch'
end
```

**Comment by klettier** [comment]
Thx this one was easy to fix, unfortunately I got the same issue : 

REPOSITORY     |     TAG       |          IMAGE ID      |      CREATED      |       VIRTUAL SIZE
----------------------|---------------|-------------------------|-----------------------|-------------------------
elasticsearch   |    1.5.2          |     49867f1bd422    |    5 days ago     |     514.5 MB
elasticsearch   |    latest          |    35f93b783f17     |   5 days ago     |     514.1 MB

CONTAINER ID   |  IMAGE |  COMMAND  | CREATED  | STATUS |   PORTS |  NAMES
---------------------|------------|------------------|----------------|-------------|-------------|--------------
7ea9845a6585 |  elasticsearch:latest  | "/docker-entrypoint. |  4 minutes ago    |   Up 4 minutes   |    9200/tcp, 9300/tcp |  elasticsearch

**Comment by jslusher** [comment]
I get the same thing. If I had to guess, it might have something to do with docker-hub registry 2.0. At any rate, this is another bug.

**Comment by rtrauntvein** [comment]
That could be @jslusher - I am mostly using this with an internal 1.0 registry

**Comment by hunterchris** [comment]
I'm having the same issue... I have defined two tags in my dockerhub: 'latest' and 'pythian-qa' and the recipe looks like this:
docker_image 'cancapital/rp-cancapital' do
  tag 'pythian-qa'
  action :pull
end

# Run container with exposed ports
docker_container 'cancapital/rp-cancapital:pythian-qa' do
  detach true
  name 'cancapital/rp-cancapital'
  port ['80:80', '443:443', '51780:51780']
end

No matter what combination of tag I use, it will always deploy the latest:
CONTAINER ID        IMAGE                             COMMAND                CREATED              STATUS              PORTS                                                                NAMES
149e6549ed20        cancapital/rp-cancapital:latest   "/bin/sh -c /run/ser   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:51780->51780/tcp   rp-cancapital

**Comment by wilb** [comment]
Seeing similar behaviour here, ironically when I want to deploy a the 2.0.1 tag of the registry container ;-)

**Comment by wilb** [comment]
Looking through the code it doesn't actually look to me like the resource pays any attention to the tag when overridden with the provider. Theoretically, overriding `image 'registry:2.0.1'` would pass the correct parameter to the docker run command, but then this is also used when trying to set the name of the container so docker bails due to invalid characters within the name. Overriding `name` within the provider doesn't seem to be doing anything either.
