### ISSUE TITLE
Containers launched with a tagged image have invalid default container names

### ISSUE THREAD

**Issue by mcoffin** [bflad/chef-docker#337]
If you launch the following docker container, it will generate an invalid container name.

```ruby
docker_container 'someimg:sometag'
```

It's also non-obvious that the `tag` attribute of `docker_container` doesn't effect the image it uses when performing the `run` or `create` actions. I fought with this for a while before figuring it out.

**Comment by fishnix** [comment]
This caught me too - to anyone finding this, the work around/fix is to use `container_name`.

Something like: 
```
docker_container 'registry' do
  container_name 'registry'
  image 'registry:2'
  detach true
  dns '8.8.8.8'
  port '5000:5000'
  publish_exposed_ports true
  env config['environment']
  volume volumes
  action :run
end
```

**Comment by someara** [comment]
This works differently with the docker_container reimplementation in master... closing for now.
(ps: you still can't use docker_container 'whatever:tag')
