### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [bflad/chef-docker#343]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by rtrauntvein** [comment]
+1 I would love to see some more activity and tests here.

We make heavy use of this cookbook also and want to see it be even more awesome and featureful!

**Comment by bflad** [comment]
Much appreciated! Let me get back to both of you over the weekend with some thoughts.

**Comment by someara** [comment]
pretty sure all the maintainers have seen this... closing this for now for issue tracker hygiene
