### ISSUE TITLE
dns_search option for docker_service is not written correctly

### ISSUE THREAD

**Issue by fcoelho** [bflad/chef-docker#346]
I've added a `docker_service`:

```ruby
docker_service 'default' do
  action [:create, :start]
  dns_search ['first.domain', 'second.domain']
end
```

The docs say that `dns_search` is supposed to be of type `String, Array`, but when I use an array (such as in the example above), the cookbook writes the docker command line as:

```
/usr/bin/docker -d --dns-search=["first.domain", "second.domain"] ...
```

when it should have been

```
/usr/bin/docker -d --dns-search=first.domain --dns-search=second.domain ... 
```

which leads to docker not starting since `["first.domain",` is not a valid domain name. If I try to use a simple string, chef fails with `Option dns_search must be a kind of Array!`

I'm running version 0.40.3 of this cookbook.

**Comment by someara** [comment]
Hello!!

Thanks for reporting this... this should be fixed up in master and will be shipped in 1.0.0

-s
