### ISSUE TITLE
Vendored docker-api not being loaded ('cannot load such file -- docker')

### ISSUE THREAD

**Issue by alecxvs** [bflad/chef-docker#351]
I've just included the latest unstable tag (0.43.0) in my project and there seems to be an issue where the docker_image provider is not loading the vendored docker gem.

When running `kitchen converge` for my project:
```
================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_image.rb
       ================================================================================
       
       LoadError
       ---------
       cannot load such file -- docker
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_image.rb:2:in `<top (required)>'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_image.rb:
       
         1:  $LOAD_PATH.unshift *Dir[File.expand_path('../../files/default/vendor/gems/**/lib', __FILE__)]
         2>> require 'docker'
         3:  
         4:  class Chef
         5:    class Provider
         6:      class DockerImage < Chef::Provider::LWRPBase
         7:        # register with the resource resolution system
         8:        provides :docker_image if Chef::Provider.respond_to?(:provides)
         9:  
        10:        def build_from_directory
        11:          i = Docker::Image.build_from_dir(
```

There isn't any configuration I need to do for this to work is there?

**Comment by jhmartin** [comment]
I'm seeing the same thing on CentOS 7 w/11.18.12.  I don't see the 'files' directory in the chef-cache, I suspect chef did not fetch it as the files aren't referenced.  Its not clear to my why the gem is vendored rather than installed via chef_gem.

**Comment by jhmartin** [comment]
https://github.com/chef/chef/blob/d8172e646d9fbf43e57bca5e20d0ac352ba9a66a/lib/chef/cookbook/synchronizer.rb#L71 is where chef-client declines to sync the contents of 'files' until something in the cookbook requests it.

**Comment by liku** [comment]
getting same on debian 8 w chef 11.18.12

**Comment by marc-** [comment]
Is there a story behind of keeping other projects sources and binaries in cookbook instead of downloading sources and build gems during cookbook execution?

**Comment by someara** [comment]
It turns out this is related to Chef 11's default behavior around file downloading.

You'll either need to upgrade to Chef 12, or set `no_lazy_load` to `true` in your client.rb

https://docs.chef.io/config_rb_client.html

-s

**Comment by mpichette** [comment]
Unfortunately this is a big problem for anyone using Opsworks. They don't support Chef 12 on linux yet and you can't modify the ```no_lazy_load``` attribute.

**Comment by chopj** [comment]
I agree with with mpichette.  This cookbook does not work with OpsWorks because of the no_lazy_load attribute

**Comment by axs221** [comment]
My team is also having this issue in OpsWorks. I have been stuck on this all night, and I don't know of a good workaround.

**Comment by someara** [comment]
This cookbook is only compatible with Chef 12. Please upgrade your
chef-client version.

**Comment by axs221** [comment]
OpsWorks unfortunately doesn't support Chef 12 at the moment. It also
doesn't support client.rb changes. I would be happy to if it was possible.

**Comment by axs221** [comment]
Here are more details about OpsWorks support. Version 12 is only currently supported for Windows deployment. We are doing Linux/Ubuntu deployment, which Chef 11.10 is the only option enabled. 

---

Chef 12.2
Chef 12.2 support was introduced in May 2015, and is used only by Windows stacks.
http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11.html

**Comment by johnschult** [comment]
@axs221 Did you ever figure out any workaround for this? Until OpsWorks supports Chef 12 on linux this cookbook is unusable there :frowning:

**Comment by axs221** [comment]
Hi John,

Unfortunately, no we didn't. We actually switched away from OpsWorks for
now, focusing on using Vagrant-AWS instead. If OpsWorks adds Chef 12
support we may reconsider, but Vagrant-AWS has been great to work with so
far.

Shawn Axsom


Shawn Axsom

**Comment by johnschult** [comment]
@axs221 Hey Shawn...  I ended up forking `0.40.x` and making the following change:

https://github.com/jhmartin/chef-docker/commit/260f0138234bbde0b90ce9a14bd4938ecfe283be

Using that version with the change in my custom cookbooks solved the problem until OpsWorks moves to Chef 12 on linux and I can use the current release.
