### ISSUE TITLE
sysconfig and epel repo breaking

### ISSUE THREAD

**Issue by jefflowrey** [bflad/chef-docker#359]
The yum-repo cookbook completely overwrites our existing epel repository with it's own ridiculous settings.

We also make changes to /etc/sysconfig/docker to add --iptables=false make sure that it doesn't destroy performance by loading the netfiler and iptables kernel modules. 

We require a method to alter the behavior of the docker chef install process and a removal of the yum-repo cookbook dependency.

**Comment by someara** [comment]
A few things.. 

1) This cookbook has no dependencies at all, so any yum issues you're having belong in another issue tracker. 

That being said, 

I'm not sure what cookbook you're talking about... I don't see a "yum-repo" cookbook on the supermarket.
I do see a "yumrepo" cookbook that's marked as deprecated. Do you mean yum-epel?

2) This cookbook replaces whatever $vendor init scripts you're used to dealing with.
The iptables settings are managed through the docker_service resource, and should end up being rendered as command line args in the sysvinit / upstart / systemd / whatever files... which are you using?

3) What platform are you on? What version of docker are you trying to use? Are you doing a fresh Docker host install, or are you trying to mutate a previously existing one?

-s
