### ISSUE TITLE
CentOS 7 errors when starting Docker

### ISSUE THREAD

**Issue by lcc2207** [bflad/chef-docker#376]
Anyone else seeing this error on CentOS 7

================================================================================
           Error executing action `start` on resource 'docker_service[default]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/provider_docker_service_systemd.rb line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl start docker ----
           STDOUT:
           STDERR: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
           ---- End output of /bin/systemctl start docker ----
           Ran /bin/systemctl start docker returned 1

----- 
here is the recipe that  is failing on CentOS 7 but works on Ubuntu 14.04

docker_service 'default' do
  tls false
  action [:create, :start]
end

**Comment by chasebolt** [comment]
Can you verify SELinux is disabled or in permissive mode with getenforce

**Comment by lcc2207** [comment]
Thank you that was the issue
