### ISSUE TITLE
executable file not found in $PATH 

### ISSUE THREAD

**Issue by jefflowrey** [bflad/chef-docker#377]
I'm trying to use the most recent version of this cookbook to run a container.

The image has a startup script that always runs when the container launches.  So when the docker container executes the parameter in "command", it actually gets passed as a parameter to the startup script.   This doesn't cause an issue, because the script ignores it's argv entirely. 

However, I'm unable to pass anything as a command.  No matter what I've tried, I keep getting "Docker::Error::NotFoundError", either complaining that the file doesn't exist, or that it's not in the path. 

The relevant parts of the resource are 
        tty true
        working_dir '/'
        open_stdin true
        env ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/opt/ibm/imaserver/bin']
        command "cd"
        action :run

Again, it doesn't matter what I put into command.  I've tried /usr/bin/true for example, and it still complains about no such file or directory.   And I have verified multiple times that the commands I'm referencing do exist in the specified location and are executable. 

I only started having this problem with this image when I upgraded to the latest version of this cookbook, that requires you specify a command on docker_container.

**Comment by someara** [comment]
What platform is your image?

'cd' isn't a binary.. its a shell built-in.
true is normally located at /bin/true, which I don't see in your PATH.

try:

sh -c 'cd /somewhere ; ./whatever'

-s

**Comment by chasebolt** [comment]
command is not a requirement for docker_container, you should be able to remove it without issue.

**Comment by jefflowrey** [comment]
Hi,
Thanks for all your input.  

Both host OS and the container release are CentOS Linux release 7.1.1503 (Core)

true is definitely in /usr/bin on this machine.  I will try a sh -c /usr/bin/true, but I have tried a /bin/bash -c.

Even if true wasn't in /usr/bin, specifying a full path to an existing executable should always find it, and stat should always return true. 

And, alas, if I comment out the command parameter, I get 
[2015-08-20T07:45:29-05:00] ERROR: docker_container[container-name] (recipe-name line 62) had an error: Docker::Error::ServerError: No command specified

Just for completeness, the metadata.rb in the docker cookbook I'm using says 
version '1.0.4'

**Comment by someara** [comment]
Okay I **think** I figured out what's probably going on here.

I suspect that the image you're trying to run has a malformed CMD directive in its Dockerfile.
Inspect it with "docker history your_image".

I added some more test resources here

https://github.com/bflad/chef-docker/blob/c1dc65afbc5d8833a354a724ad3537eeb2bb57b4/test/cookbooks/docker_test/recipes/container.rb#L324-L326

The first go around, I gave it an invalid format, which produced the error you described.

CMD '/bin/ls -la /'

^ That tries to run a binary named '/bin/ls -la /'

If you remove the quotes, it will run it in "shell form" mode (it automatically starts sh -c for you)

The recommended format is exec form: 
CMD [ "argv[0]", "argv[1], "...", "argv[n]" ]

https://docs.docker.com/reference/builder/#cmd

I bet that's it.

-s

**Comment by jefflowrey** [comment]
Hi - 
Unfortunately we aren't using a CMD directive. 
The Dockerfile has the following directives:
      FROM
      MAINTAINER
      WORKDIR
     RUN (two of these, actually, to do some prep)
     ENTRYPOINT
     ONBUILD ... ADD

The ENTRYPOINT is the one that defines the script that runs.  It does have quotes, but that's because it's an array - ["scriptname"], not "scriptname"

**Comment by someara** [comment]
I'm at a loss to reproduce this then... 
I've got two resources exercising entrypoint, one with a command, and one without.

https://github.com/bflad/chef-docker/blob/21fd17e073b683d1f33036ef28e063b1cbb01251/test/cookbooks/docker_test/recipes/container.rb#L304-L306

**Comment by jefflowrey** [comment]
Is there additional trace or debug I can provide? 

Can you reproduce the required CMD error?

**Comment by someara** [comment]
Linking to a gist/pastbin the complete stack trace from the chef-client run would be the most helpful thing.

**Comment by jefflowrey** [comment]
Again, really glad for the help, particularly so promptly.

Stack trace at http://pastebin.com/twjnGwE5

**Comment by chasebolt** [comment]
Update your command with /bin/true, currently you have /usr/bin/true.

**Comment by jefflowrey** [comment]
As I said, /usr/bin/true *does* exist.

But here's /bin/true http://pastebin.com/mWXCYP6s

**Comment by chasebolt** [comment]
Can you give us the full details of your docker_container and Dockerfile? I am unable to reproduce this on the latest version with the relevant parts of the resource you pasted in the first post.

**Comment by jefflowrey** [comment]
I've changed the values to protect the innocent, but I've left the syntax the same. 

http://pastebin.com/yf0PpC1y

Again, I didn't have this problem when command wasn't required.

**Comment by someara** [comment]
This is really bizarre... what Docker engine version?

**Comment by jefflowrey** [comment]
docker --version
Docker version 1.7.1, build 3043001/1.7.1

**Comment by someara** [comment]
What does the equivalent "docker run" command do?
-s

**Comment by jefflowrey** [comment]
8d606dd4a5a8b84d3f60f6ea7ca8408700dc700f8844d3babe57f6a3ae9b4e25
Error response from daemon: Cannot start container 8d606dd4a5a8b84d3f60f6ea7ca8408700dc700f8844d3babe57f6a3ae9b4e25: [8] System error: exec: "/bin/true": stat /bin/true: no such file or directory

**Comment by jefflowrey** [comment]
Oh, and.  That was without the --env and -v parameters.

**Comment by jefflowrey** [comment]
And, the command while I'm at it.
 docker run -i=true -t=true  --memory=17179869184 -d=true -it --net="host" -P --name="container-name" -w="/" 'image-name' /bin/true

**Comment by jefflowrey** [comment]
The fix I would really like to see is the removal of the requirement for command.

**Comment by chasebolt** [comment]
can you checkout the latest version from master branch and give that a spin? comment out the command, I am curious if it still errors out with Docker::Error::ServerError: No command specified.

**Comment by someara** [comment]
The command property isn't required by the resource.

https://github.com/bflad/chef-docker/blob/21fd17e073b683d1f33036ef28e063b1cbb01251/libraries/resource_docker_container.rb#L12

There's a test exercising a defined entrypoint with a blank command here:

https://github.com/bflad/chef-docker/blob/21fd17e073b683d1f33036ef28e063b1cbb01251/test/cookbooks/docker_test/recipes/container.rb#L309-L314

Since you're getting the same error with the Docker CLI as the docker_container resource, that means the problem lies with the engine, the image, or some combination of the two.

Given that and the fact that I can't reproduce this, I'm going to close the ticket for lack of actionability.

PS: Let me know when you figure out what's wrong.. I'm definitely curious!

-s
