### ISSUE TITLE
pull_image leaves left over untagged images on update

### ISSUE THREAD

**Issue by chasebolt** [bflad/chef-docker#378]
pull_image should call the remove_image with the original image id if the resource has been updated. this should be an option for docker_image, 'prune_on_update' default to true.

**Comment by chasebolt** [comment]
i dont think this is a viable option for docker_image now that I have looked further into it. if there is a container running from the original image, you will be unable to prune it.

a couple of options
1) create a new resource that prunes all images based off of the repotags == ['<none>:<none>']
2) same as 1 except we make it part of docker_container or docker_images, this would prune all images even if it never belonged to the resource.
3) we close this, document the behavior, and leave it up to the discretion of ops to do clean up.

**Comment by rtrauntvein** [comment]
We handle this clean with a recipe that drops https://github.com/spotify/docker-gc into cron.daily or cron.hourly 

It has some logic there to only remove unused images

**Comment by chasebolt** [comment]
thanks for that @rtrauntvein! this sways me in the direction of creating a docker_gc resource that functions the same way; with an exclude array for containers and images.

**Comment by someara** [comment]
Does the docker cli behave the same way?

Also, while I like the idea of a docker_gc resource... I'd rather not add something like that right now.
Scope creep is a hell of a drug

**Comment by someara** [comment]
Closing this for now, since there doesn't seem to be anything actionable to do in docker_image at the moment
