### ISSUE TITLE
docker_container ulimits syntax

### ISSUE THREAD

**Issue by rudijs** [bflad/chef-docker#385]
Hi,

What's the correct syntax for the [ulimits option](https://github.com/bflad/chef-docker/search?utf8=%E2%9C%93&q=ulimits) for docker_container?

I've tried both Array and Hash with errors:

```
  ulimits [
              "nofile=40960:40960",
              "core=100000000:100000000",
              "memlock=100000000:100000000"
          ]
```

    Docker::Error::ServerError: json: cannot unmarshal string into Go value of type ulimit.Ulimit

```
  ulimits ({
              :nofile => "40960:40960",
              :core => "100000000:100000000",
              :memlock => "100000000:100000000"
          })
```

    Docker::Error::ServerError: json: cannot unmarshal object into Go value of type []*ulimit.Ulimit

This is for the [official Couchbase](https://hub.docker.com/_/couchbase/) image.

Command line works OK for me like this:

    sudo docker run --rm --name couchbase -p 8091:8091 -p 11210:11210 -p 11211:11211 --ulimit nofile=40960:40960 --ulimit core=100000000:100000000 --ulimit memlock=100000000:100000000 couchbase:community-3.0.1

I've tinkered for a while but just can't seem to get the recipe syntax right so am stuck.

Advice to tips here very much appreciated.

Thanks.

**Comment by someara** [comment]
Hi. 

Right now its just blindly shoveling data into the Docker remote API... let me see if I can figure out the format it wants....

**Comment by someara** [comment]
It turns out the syntax you'll need to use right now is less than delightful

https://github.com/bflad/chef-docker/commit/f5b735c662810b92dff68806a66893c06715f0ab

This is one of those weird areas of the API that eat data one way and report it back another.
In the future I'll probably end up adding a format helper so this becomes more intuitive (like port).

**Comment by someara** [comment]
For anyone stumbling across this on Google:

As of chef-docker 1.0.x, and Docker 1.8.1, the ulimits syntax is

```ruby
docker_container 'ulimits' do
  repo 'alpine'
  tag '3.1'
  command 'nc -ll -p 778 -e /bin/cat'
  port '778:778'
  ulimits [
    { 'Name' => 'nofile', 'Soft' => 40960, 'Hard' => 40960 },
    { 'Name' => 'core', 'Soft' => 100000000, 'Hard' => 100000000 },
    { 'Name' => 'memlock', 'Soft' => 100000000, 'Hard' => 100000000 }
  ]
  action :run
end
```

**Comment by rudijs** [comment]
@someara Thanks for digging that out Sean.

I did grep the code for ulimits but I only have the Gem not the source.

I'll clone the repo next time so I can be more thorough before bugging the team here.

Thanks again, this is a great cookbook, very much appreciated.

**Comment by someara** [comment]
I actually figured it out by searching for "ulimits" on this page
