### ISSUE TITLE
tls container stopping when using cookbook?

### ISSUE THREAD

**Issue by lcc2207** [bflad/chef-docker#389]
If I run this command the registry works perfectly 
docker run -d -p 5000:5000 --restart=always --name registry1 -v /opt/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/cert.crt  -e REGISTRY_HTTP_TLS_KEY=/certs/cert.key registry:2

But if I run the cookbook section below the container stop immediately.  any thoughts/advice?

docker_container 'registry' do
  container_name 'registry'
  image 'registry'
  env ['REGISTRY_HTTP_TLS_CERTIFICATE=/opt/certs/cert.crt', 'REGISTRY_HTTP_TLS_KEY=/opt/certs/cert.key']
  volumes ['/opt/certs/certs']
  port '5000:5000'
  tag 2
  action :run
end

**Comment by someara** [comment]
You need "binds" instead of "volumes" there.
volumes works like the VOLUMES directive in a Dockerfile.

**Comment by someara** [comment]
PS: There's a registry recipe example in test/cookbook/docker_test/recipes that sets one up for to test the push action on docker_image. Might be helpful

**Comment by lcc2207** [comment]
I tried binds same result, I'll look at the test more too

**Comment by someara** [comment]
You'll also need to set the mount point with a colon

binds ['/hostbits:/bits', '/more-hostbits:/more-bits']

-s
