### ISSUE TITLE
Add test coverage for latest Docker on Ubuntu 14.04

### ISSUE THREAD

**Issue by joegoggins** [bflad/chef-docker#399]
It would be great if this cookbook had automated tests for this Ubunut 14.04, it would make me feel like I was going with the infrastructure grain Docker is setting. This OS is the one that Docker appears to endorse most as the happy, easy path (as indicated by the default OSes used with [`docker-machine create`](https://docs.docker.com/machine/drivers/aws/) . 

What is the main work that needs to be done to get test-kitchen coverage for Ubuntu 14.04? Are there any hidden complexities folks know that is holding this up? (i may take a crack at adding a test-suite for 1.8.1 + 14.04)

*Some context for why I'm asking for this*:

I'm spinning a Dockerhost today on AWS and was planning on using this cookbook to do so. However, when I saw Ubuntu 14.04 wasn't tested, I had a second thought of doing initial machine provisioning with `docker-machine` because I trust the underlying dependencies for this OS would be correct, and that I'd be on the Docker happy path. If I went that route, I wouldn't use `docker_service` LWRP for this, just the other LWRPs for containers + images.

**Comment by someara** [comment]
It actually is tested on 14.04 via the kitchen.cloud.yml.. I'll fix the readme to reflect reality next time I'm in front of a real computer =)

**Comment by joegoggins** [comment]
For for this silly GH issue sir, I don't know why I didn't look there first before writing this issue, doh!

**Comment by someara** [comment]
It's my fault!
