### ISSUE TITLE
Release 1.0.13 breaks rspec

### ISSUE THREAD

**Issue by jrosenboom** [bflad/chef-docker#407]
When testing a cookbook that includes the docker cookbook, since 1.0.13 we get errors like this:

```
================================================================================
Recipe Compile Error in /tmp/d20150831-7686-1rjxsb9/cookbooks/docker/libraries/matchers.rb
================================================================================

NoMethodError
-------------
undefined method `allowed_actions' for Chef::Resource::DockerContainer:Class

Cookbook Trace:
---------------
  /tmp/d20150831-7686-1rjxsb9/cookbooks/docker/libraries/matchers.rb:15:in `block in <top (required)>'
  /tmp/d20150831-7686-1rjxsb9/cookbooks/docker/libraries/matchers.rb:5:in `each'
  /tmp/d20150831-7686-1rjxsb9/cookbooks/docker/libraries/matchers.rb:5:in `<top (required)>'

Relevant File Content:
----------------------
/tmp/d20150831-7686-1rjxsb9/cookbooks/docker/libraries/matchers.rb:

  8:  
  9:      if Gem.loaded_specs['chefspec'].version < Gem::Version.new('4.1.0')
 10:        ChefSpec::Runner.define_runner_method(name)
 11:      else
 12:        ChefSpec.define_matcher(name)
 13:      end
 14:  
 15>>     resource.allowed_actions.each do |action|
 16:        define_method("#{action}_#{name}") do |resource_name|
 17:          ChefSpec::Matchers::ResourceMatcher.new(name, action, resource_name)
 18:        end
 19:      end
 20:    end
 21:  end
 22:  
```

If I explicitly pin the cookbook version to 1.0.12, everything works fine. This seems to be related to this commit: https://github.com/bflad/chef-docker/commit/4fd3083d3844a292039c0aa8882c2068676b5f7b

**Comment by someara** [comment]
There's a new one...
specs pass on my laptop (ChefDK 0.7.0) https://gist.github.com/someara/7d5d98e5bb75f69c9a07

I noticed that Travis is broken with (different a error message), which I chocked up to mismatched ChefDK versions, and was planning on investigating later.

Can you try 1.0.16 and let me know relevant versions?

-s

**Comment by jrosenboom** [comment]
Ah, o.k., the errors only seem to be seen with ChefDK 0.6.2 or smaller, i.e. with Chef <= 12.3. Upgrading to 0.7.0 helped, my tests are running fine with that.

**Comment by someara** [comment]
Good to know! thanks!

**Comment by jklare** [comment]
the method allowed_actions was introduced here: https://github.com/chef/chef/commit/236570dc9605ac312b44508b1c3a6a0e7c19b4dc
