### ISSUE TITLE
Regression in 1.0.16 docker_container - invalid network configuration

### ISSUE THREAD

**Issue by kkeane** [bflad/chef-docker#408]
The 1.0.16 cookbook will create a container that does not start. The 1.0.14 cookbook works fine.

The error message is: "invalid network configuration: default"

I used the mysql:5.7 image from docker hub and this resource:

docker_container containername do
   action         :run
   repo           image
   tag            tag
   command        "mysqld"
   port           "3306:3306"
   restart_policy "always"
   container_name containername
   hostname       container_hostname
   env            "MYSQL_ROOT_PASSWORD=#{tmppassword}"
   binds          ['/var/lib/mysql:/var/lib/mysql']
   notifies       :run_if_missing, "docker_container[Mysql_set_root_password]", :immediate
 end

The image and tag I used are mysql:5.7 (the official mysql docker image from hub.docker.com)

container_name and container_hostname can probably be set to anything you like.

**Comment by kkeane** [comment]
Additional information: This is on CentOS 6.7 and docker 1.6.2 build 7c8fca2/1.6.2 - installed from the epel repository. Epel lists this docker version as 1.5-5.el6

**Comment by kkeane** [comment]
docker inspect shows that the NetworkMode is set to an empty string in 1.0.14, but to the word "default" in 1.0.16.

**Comment by someara** [comment]
Fix released in 1.0.17
