### ISSUE TITLE
docker_container should have create_if_missing action

### ISSUE THREAD

**Issue by kkeane** [bflad/chef-docker#409]
The docker_container resource has a build and a create action, but only build has a corresponding _if_missing action. For containers that should only be created (such as data only containers), there also should be a create_if_missing action.

**Comment by someara** [comment]
In `docker_container`, create naturally behaves this way.. The `docker_image` build_if_missing is really only there to address the fact that build is necessarily dumb.

**Comment by someara** [comment]
To be clear, `:create` is what you want for a data-only container, `:run` will converge it through the `:create:` and `:start` states
