### ISSUE TITLE
Incorrect handling of Dockerfile overrides in docker_container

### ISSUE THREAD

**Issue by kkeane** [bflad/chef-docker#410]
This is related to #409 
When a container already exists and the command was specified in the docker file, but not in a property of the docker_container resource, the resource will delete and recreate the container on every chef run. The following log came from a run with the entry
CMD ["/noaction"] in the dockerfile.

    * docker_container[mycontainer] action create
      * log[command - :["/noaction"]: ::] action write
      * log[command - :["/noaction"]: ::] action write
      - deleting mycontainer
      * log[command - :["/noaction"]: ::] action write
      - creating mycontainer
      * log[command - :["/noaction"]: ::] action write

**Comment by someara** [comment]
Aha!  Dueling sources of truth.

This is going to be an issue for anything that a Dockerfile lets you insert into an image's metadata..
CMD, ENTRYPOINT, VOLUME, USER, and EXPOSE.

The correct thing to do here would be to mimic the docker CLI's behavior of "overriding" them if present.

PS, those log resources were for debugging while implementing #309 .. I've removed them because they're unreliable.

**Comment by someara** [comment]
This is fixed up in 1486aa2855194a504717e54508f26a7e2cfd0144, released as 1.0.20

**Comment by kkeane** [comment]
I don't think this is fixed yet; I'm still having the same problem in 1.0.21. Without the logging entries, I don't know exactly what triggers it.

**Comment by someara** [comment]
Which properties are you specifying on your docker_container resource?

**Comment by kkeane** [comment]
I backported the logging from 1.0.17 into 1.0.21, and the following properties are the culprits:
    
    * log[working_dir - :/var/www/redacted.com: ::] action write
    * log[log_config - :{"Type"=>"json-file", "Config"=>{}}: ::] action write
    * log[volumes - :{"/var/www/redacted.com/"=>{}}: ::] action write
    * log[working_dir - :/var/www/redacted.com: ::] action write

My container resource looks like this

   docker_container("redacted") do
      action [:create]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_container
      cookbook_name "nctc-sites"
      repo "nctc/redacted"
      tag "latest"
      restart_policy "no"
      container_name "redacted"
      host_name "redacted"
      dns [redacted - two IPv4 addresses]
      detach true
    end

And the Dockerfile:

 Dockerfile for redacted
# Auto generated by chef
# Do not edit

FROM debian:latest

MAINTAINER Kevin Keane

RUN mkdir -p /var/www/redacted

WORKDIR /var/www/redacted

# copy the html directory, and if it exists also the configdir
COPY html/ html/

COPY *.conf ./

CMD echo "This is a data-only container for the Web site redacted"

VOLUME /var/www/redacted/

**Comment by kkeane** [comment]
In a different docker_container resource, I saw the exposed_ports and network_mode properties show up in that logging, too.

**Comment by someara** [comment]
What version of Docker are you using? 1.6? 1.8?

I'll send some time later today attacking this and trying to craft some better debug logging. 

In retrospect, resolving #309 turned out to cause a lot more trouble than I anticipated...1.0.15 should have really been 1.1.0. =\

**Comment by kkeane** [comment]
1.7.1, running on CentOS 6.7. Installed from the epel repository.

**Comment by someara** [comment]
I'm pretty confident this is fixed up in v1.0.24... can you verify before I close it?

**Comment by kkeane** [comment]
Yes, this appears to be fixed now. Thank you very much!﻿

Kevin Keane

The NetTech

﻿http://www.4nettech.com

Our values: Privacy, Liberty, Justice

See https://www.4nettech.com/corp/the-nettech-values.html



-----Original message-----

**Comment by someara** [comment]
closing with much satisfaction,
-s
