### ISSUE TITLE
udev support needed for devicemapper support

### ISSUE THREAD

**Issue by docwhat** [bflad/chef-docker#415]
Because the binaries on get.docker.com are statically built, they don't have udev support, which causes the devicemapper storage to not work reliably (see [docker issue #4036](https://github.com/docker/docker/issues/4036#issuecomment-111174341)).

Another alternative is to use the [new yum and apt repos](https://blog.docker.com/2015/07/new-apt-and-yum-repos/).

**Comment by someara** [comment]
dupe #345
