### ISSUE TITLE
docker_container links property only uses first entry

### ISSUE THREAD

**Issue by kkeane** [bflad/chef-docker#416]
In the docker_container resource, if you use the links property to set up more than one link, only the first one will be used.

docker_container "mycontainer" do
  action :run
  links [ 'database:db', 'appserver:app' ]
end

docker inspect --format='{{ .HostConfig.Links }}' mycontainer will show
[/database:db]

Doing the equivalent with the docker cli will show:
[/database:db /appserver:app]

**Comment by someara** [comment]
Hello!

I can't seem to reproduce this.... I've tested it on 1.8.2, 1.7.1, and 1.6.2

I added tests to try and recreate this here https://github.com/bflad/chef-docker/commit/2cea6b909aec719864ff685d965cb7e3680b63c2

This probably got fixed up somewhere along the line during @jperville 's work to fix the override behavior.

Closing for now, please re-open if its still an issue.

-s
