### ISSUE TITLE
ChefSpec Matchers only work with chef 12.4+

### ISSUE THREAD

**Issue by JamesAwesome** [bflad/chef-docker#418]
The ChefSpec matchers included with this cookbook now use the `allowed_actions` method for each custom defined resource in order to create it's matchers [See this commit](https://github.com/bflad/chef-docker/commit/4fd3083d3844a292039c0aa8882c2068676b5f7b). 

Because the `allowed_actions` method was [introduced in chef 12.4](https://www.chef.io/blog/2015/06/24/chef-client-12-4-0-released/) these matchers now break ChefSpec compatibility with chef versions < 12.4. 

This should be (preferably) corrected and/or noted in the `README.md`.

**Comment by someara** [comment]
I've updated the README to reflect the 12.4 dependency.
