### ISSUE TITLE
Does not support multiple port mappings

### ISSUE THREAD

**Issue by jonathanmorley** [bflad/chef-docker#419]
I haven't managed to narrow down which (first, last, ...) port it uses, but only one port in the resource gets used.

docker_container 'test' do
  repo node['image']
  tag node['version']
  port '80:80'
  port '8081:8081'
end

Will only map port 8081

**Comment by chasebolt** [comment]
You need to pass it an array.

docker_container 'test' do
  repo node['image']
  tag node['version']
  port ['80:80', '8081:8081']
end

**Comment by bflad** [comment]
Hi, I believe you're looking for the array syntax with multiple ports:
https://github.com/bflad/chef-docker/blob/master/libraries/resource_docker_container.rb#L45

Does this work for you?

```ruby
docker_container 'test' do
  repo node['image']
  tag node['version']
  port ['80:80', '8081:8081']
end
```

**Comment by someara** [comment]
@jonathanmorley as Chase and Brian stated, you're looking for the array syntax. 

PS: This is going to be universal for all chef resources... when you list a property multiple times like that, the last one will "win", because its calling the set_or_return method under the hood.

-s

**Comment by sandrotosi** [comment]
can the documentation be updated for this then? `port - The port configuration to use in the container. Matches the syntax used by the docker CLI tool.` but the cli tool allows to pass multiple `-p <X>:<Y>` options, so maybe adding an example for multiple ports would be helpful -- thanks
