### ISSUE TITLE
docker_image fails if run right after docker_service 

### ISSUE THREAD

**Issue by lcc2207** [bflad/chef-docker#421]
Has anyone run into this 
docker_image fails if run right after docker_service on the initial run but the images gets pulled down on the second run. 

Errors with   read timeout reached

docker_image 'jenkins' do
  read_timeout 600
  write_timeout 600
  repo 'jenkins'
  tag 'latest'
  action :pull_if_missing
end

**Comment by someara** [comment]
I suppose we need to devise a way to poll the service or "ready" before exiting the provider action... any ideas off the top of your head?

**Comment by jonathanmorley** [comment]
ruby_block 'wait for tomcat' do
      block do
        true until ::File.exists?('/var/run/docker.sock')
      end
    end

is what I have been using

**Comment by someara** [comment]
I've added wait blocks in 1.0.41. This should be good to go.
