### ISSUE TITLE
docker_container and port syntax

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#427]
I have noticed a difference related to port bindings between the containers created with the cookbook (currently version 1.0.24) and those created with an equivalent docker client command-line.

I create my container in the cookbook like this:
```ruby
docker_container 'my-app' do
  repo 'busybox'
  tag 'ubuntu-14.04'
  port ['80', '22']
  ...
end
```

I am trying to write an assertion in my cookbook test suite to check whether the container is publishing a given port. With version 0.37 of this cookbook (which used 'docker' client command-line instead of the API), I would just search for `80/tcp` in the output of `docker inspect --format='{{ .HostConfig.PortBindings }}' for example.

However, now that the containers are created using the docker API, I can only match for `80` (without 'tcp' at the end), which means that containers created by the cookbook and by the command-line API do not docker-inspect the same anymore.

Here is a sample shell session demonstrating the problem.

```sh
# when we start, we are supposed to have converged the node and the `my-app` container exists.
root@docker-ubuntu-1404:~# docker inspect --format='{{ .HostConfig.PortBindings }}' my-app
map[22:[{ }] 80:[{ }]] # <--- new format, no '/tcp' present
root@docker-ubuntu-1404:~# docker rm -f my-app
my-app
# now I recreate the container manually using equivalent command-line
root@docker-ubuntu-1404:~# docker create --name="my-app" --publish="22" --publish="80" busybox:ubuntu-14.04 /bin/top
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
dd7e74178fc99a23e1781028b539c2f19ba039bab17c7856309389fdbd3fe856
root@docker-ubuntu-1404:~# docker inspect --format='{{ .HostConfig.PortBindings }}'
my-app
map[22/tcp:[{ }] 80/tcp:[{ }]]  # <-- note the presence of /tcp in the output.
```

Would it be possible to change the way port bindings are created in the cookbook to follow the convention of the docker command-line client?

**Comment by someara** [comment]
That makes sense to me. 

I won't have very much time to work on this over the next week, so if you'd like to take a crack at a PR, I can point you in the right direction:

The test cookbook exercises ports beginning here -  https://github.com/bflad/chef-docker/blob/master/test/cookbooks/docker_test/recipes/container.rb#L39

... and the serverspec assertions are here - Just add the inspect line 

https://github.com/bflad/chef-docker/blob/4537b99c903ff650e34137daba7b09af6db001d8/test/integration/resources-182/serverspec/assert_functioning_spec.rb#L140

The logic to generate the port data begins somewhere around here

https://github.com/bflad/chef-docker/blob/4537b99c903ff650e34137daba7b09af6db001d8/libraries/helpers_container.rb#L62

And is consumed here

https://github.com/bflad/chef-docker/blob/4537b99c903ff650e34137daba7b09af6db001d8/libraries/provider_docker_container.rb#L113

-s

**Comment by jperville** [comment]
Sure @someara , will try to schedule it for the end of week too (together with other PRs on your great cookbook; I'm currently porting my existing application cookbook to version 1.x of this cookbook, so discovering a lot of very subtle issues).
