### ISSUE TITLE
docker_container and hostname/domainname parsing

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#429]
Given a container declared with a hostname attribute containing a domain part:

```ruby
docker_container 'my-test-app' do
  repo 'busybox'
  tag 'ubuntu-14.04'
  hostname 'my-test-app.mydomain'
  command '/bin/top'
end
```

With the container created by the cookbook, hostname and domain name are not split: the hostname is copied verbatim while the domain name field is left empty:

```
root@docker-ubuntu-1404:~# docker inspect --format='{{ .Config.Hostname }}' my-test-app
my-test-app.docker-ubuntu-1404
root@docker-ubuntu-1404:~# docker inspect --format='{{ .Config.Domainname }}' my-test-app
```

When the container is created with an equivalent docker client command line (eg. `docker run --name=my-test-app --hostname 'my-test-app.mydomain' ubuntu:14.04 /bin/top`) then the hostname and domain names are split in the docker inspect configuration:

```sh
root@docker-ubuntu-1404:~# docker inspect --format='{{ .Config.Hostname }}' my-test-app
my-test-app
root@docker-ubuntu-1404:~# docker inspect --format='{{ .Config.Domainname }}' my-test-app
docker-ubuntu-1404
```

Have no clue if this is important bug, but while I'm examining the differences of docker inspect between a cookbook-managed and a manually-created container (see #427 and #428) I may as well report it.

**Comment by jperville** [comment]
For information, the `docker run` command does not have a domainname option, just a hostname (which may include a domain part). I would implement a PR which splits the hostname into hostname and domainname transparently to emulate the `docker run --hostname` behavior.

**Comment by someara** [comment]
Interesting.

I've always been a fan of using FQDNs as a hostnames to avoid glibc
weirdness and deal with Solaris and friends.

If we implemented the Docker CLI behavior emulation, it would make that
difficult or impossible.

Also of concern is the.four.dots.problem... where does the hostname end and
the domain name begin?

-s

**Comment by jperville** [comment]
After testing, for the docker client the hostname is what is left of the first dot, and the domain name is what is right of that first dot.

```json
{
        "Hostname": "my-test-app",
        "Domainname": "x.y.z.docker-ubuntu-1404"
}
```

That will be quite easy to emulate, I can get a PR out relatively quickly (once I have sorted out #428).

**Comment by someara** [comment]
I think I'd like to leave this one as is...

The current behavior is simple and explicit.
The emulated behavior is arbitrary, ambiguous, and precludes the
fqdn-as-hostname scenario (which I use)
Also, what about the case where both hostname and domainname are specified
on the resource?

-s

**Comment by jperville** [comment]
I don't mind leaving as it is, I will just update my cookbooks for the new behavior.

**Comment by someara** [comment]
thanks for bringing this up!

**Comment by muikrad** [comment]
This behavior has changed with Docker 1.11 - placing dots in the --hostname no longer populates domainname as before, and --domainname is not supported either. I am trying to find more information about this new behavior - anyone cares to chime in?

**Comment by sanmai-NL** [comment]
@jonapich: would like to share what you found out about domainname with >=1.11?
