### ISSUE TITLE
/usr/lib/tmpfiles.d/docker.conf is missing the directory path

### ISSUE THREAD

**Issue by docwhat** [bflad/chef-docker#434]
On my systems the file `/usr/lib/tmpfiles.d/docker.conf` contains:

```
d  0755 root root -
```

Looking at the template, it seems that `<%= @run_dir %>` isn't being substituted correctly.

And indeed, it looks like there is no variable `@run_dir` set.

This generates system log entries like:

```
[/usr/lib/tmpfiles.d/docker.conf:1] Path '0755' not absolute.
```

**Comment by someara** [comment]
Fixed in 1.0.29
