### ISSUE TITLE
How to run the serverspec?

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#438]
I have been trying to run the serverspec for this cookbook with the following steps:
```sh
$ kitchen list # to see which suites are available
$ kitchen converge resources-ubuntu-1504 # converges fine
$ kitchen setup resources-ubuntu-1504
$ kitchen verify resources-ubuntu-1504
```

I can converge just fine, but the setup then verify steps seems to be no-ops, as show the trace below:
```sh
jp440p:chef-docker(195m|redeploying-unstarted-containers!) $ kitchen setup resources-ubuntu-1504 
-----> Starting Kitchen (v1.4.2)
-----> Setting up <resources-ubuntu-1504>...
       Finished setting up <resources-ubuntu-1504> (0m0.00s).
-----> Kitchen is finished. (0m0.41s)
jp440p:chef-docker(195m|redeploying-unstarted-containers!) $ kitchen verify resources-ubuntu-1504
-----> Starting Kitchen (v1.4.2)
-----> Verifying <resources-ubuntu-1504>...
       Preparing files for transfer
       Transferring files to <resources-ubuntu-1504>
       Finished verifying <resources-ubuntu-1504> (0m0.00s).
-----> Kitchen is finished. (0m0.42s)
jp440p:chef-docker(195m|redeploying-unstarted-containers!) $ 
```

Did I do something wrong in my procedure to run the serverspec? I think the CONTRIBUTING.md document should be updated to describe the current procedure, since it still talks about `minitest-chef`.

**Comment by someara** [comment]
Are you on master? That was briefly broken when expanding the matrix to explicitly test versions... but only for a moment.

It should be 

kitchen test resources-182-ubuntu-1504
of

kitchen test resources-182-ubuntu-1504
kitchen verify resources-182-ubuntu-1504
kitchen destroy resources-182-ubuntu-1504

-s

**Comment by jperville** [comment]
Yes, I am on master (still have one more PR to work on). I will try your suggestions in a couple minutes and will let you know of my success.

**Comment by jperville** [comment]
Actually, the instances returned by `kitchen list` are:

```sh
Instance                   Driver   Provisioner  Verifier  Transport  Last Action
resources-centos-70        Vagrant  ChefZero     Busser    Ssh        <Not Created>
resources-debian-81        Vagrant  ChefZero     Busser    Ssh        <Not Created>
resources-fedora-21        Vagrant  ChefZero     Busser    Ssh        <Not Created>
resources-ubuntu-1204      Vagrant  ChefZero     Busser    Ssh        <Not Created>
resources-ubuntu-1404      Vagrant  ChefZero     Busser    Ssh        Converged
resources-ubuntu-1504      Vagrant  ChefZero     Busser    Ssh        Converged
notifications-ubuntu-1504  Vagrant  ChefZero     Busser    Ssh        <Not Created>
```

There is no `resources-182-ubuntu-1504` instance for example.
Working on today's master kitchen.yml : https://github.com/bflad/chef-docker/blob/640f15df46306192d4db70983e1003e6ef4b501d/.kitchen.yml

**Comment by someara** [comment]
Oh derp.

I only updated the .kitchen.cloud.yml and forgot about the .kitchen.yml.

Just pushed a fix to master.

-s

**Comment by jperville** [comment]
Thank you very much @someara . I was able to run `kitchen test resources-182-ubuntu-1404` and validate my last PR. You can close this issue now.
