### ISSUE TITLE
Error: could not find recipe default for cookbook docker

### ISSUE THREAD

**Issue by petecarapetyan** [bflad/chef-docker#453]
Previously working cookbook which included docker cookbook is now broken?

Here is the error message

Chef::Exceptions::RecipeNotFound
       --------------------------------
       could not find recipe default for cookbook docker

**Comment by chasebolt** [comment]
This is a library and not a recipe. You only need to include the cookbook in your metadata and then you may call the docker_* providers in your cookbooks.

**Comment by someara** [comment]
Hi Peter!

That is correct.... as of 1.0.0 of this cookbook, this cookbook is resource based instead of recipe based.

-s
