### ISSUE TITLE
icc parameter to docker_service logic is off

### ISSUE THREAD

**Issue by BetaKevin** [bflad/chef-docker#462]
https://github.com/bflad/chef-docker/blob/4e843c10f12e57e7369b26fa770cc86f166cd7ee/libraries/helpers_service.rb#L154

The default value of icc is true according to this documentation
https://docs.docker.com/reference/commandline/daemon/

I want to be able to set icc to false but doing so results in it not be adding to the parameters of the daemon.  It looks like it will only add the parameter if its true but that doesn't really matter as the default is true.

docker_service 'default' do
  action [:create, :start]
  log_level :info
  icc false
end

Results in:
ExecStart=/usr/bin/docker daemon --log-level=info

I want:
ExecStart=/usr/bin/docker daemon --log-level=info --icc=false

**Comment by someara** [comment]
thanks for reporting this

**Comment by BetaKevin** [comment]
thank you so much for the quick response and release!!!  Amazing work.

**Comment by BetaKevin** [comment]
https://github.com/bflad/chef-docker/pull/464/files#diff-51c36c8f820c0f1bf918f59163c3d498L154

Sorry, but this doesn't work correctly.  "if new_resource.icc" is false (in my case) and will still result in not having icc in the parameters of the command.

**Comment by chasebolt** [comment]
fixed up, conditional was incorrect because of false :cry:
