### ISSUE TITLE
Sysvinit depends on insserv being installed

### ISSUE THREAD

**Issue by mattrobenolt** [bflad/chef-docker#466]
When just trying to do a simple:
```ruby
docker_service 'default' do
  version '1.8.2'
  provider Chef::Provider::DockerService::Sysvinit
  actions [:create, :start]
end
```

We end up with a missing dependency on `/sbin/insserv`.

`service[docker] (/var/chef/cache/cookbooks/docker/libraries/provider_docker_service_sysvinit.rb line 33) had an error: Errno::ENOENT: No such file or directory - /sbin/insserv`

This is on Ubuntu Precise.

**Comment by bflad** [comment]
Sorry for the silly question but which OS?

**Comment by mattrobenolt** [comment]
> This is on Ubuntu Precise.

**Comment by someara** [comment]
I switched the underlying provider from ::Insserv to ::Debian in v1.0.43
I *think* this should fix you up... please repoen if needed.
