### ISSUE TITLE
Invalid Sysvinit script on multiple-hosts docker_service

### ISSUE THREAD

**Issue by drazzib** [bflad/chef-docker#476]
Hi !

I'm using a `docker_service` declaration which is similar to the one in `README.md`. I've multiple `hosts` values to bind daemon on TCP + local socket :
```ruby
docker_service 'default' do
  version '1.8.2'
  host ['unix:///var/run/docker.sock', "tcp://0.0.0.0:2375"]
  provider Chef::Provider::DockerService::Sysvinit
  action [:create, :start]
end
```

1. Generated `/etc/init.d/docker` contains the valid docker daemon parameters ```
/usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 ``` which is great ! :)

2. `/etc/init.d/docker` environnement variables (used for status command) are invalid ```export DOCKER_HOST=["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]```
=> DOCKER_HOST should only include a single value
As a temporary workaround, I've patched `templates/default/sysvinit/docker.erb` to only render first host from array : ```
export DOCKER_HOST=<%= @docker_host %>``` is replaced by ```
export DOCKER_HOST=<%= @docker_host.first %>```

3. Same goes for `docker-wait-ready` bash script inside `libraries/provider_docker_service_sysvinit.rb` : I've replaced  ```env_h['DOCKER_HOST'] = new_resource.host unless new_resource.host.nil?```
by ```env_h['DOCKER_HOST'] = new_resource.host.first unless new_resource.host.nil?```

IMHO, one way to handle this is to allow separate attributes for Docker daemon binding (-H opts) and for Docker client connection (`DOCKER_HOST` environnement variable).
What do you think about this ?

Regards,
Damien

**Comment by chasebolt** [comment]
Are you using the latest version with partial tls fix? This fixed a lot of
issues with declaring multiple host bindings.

**Comment by drazzib** [comment]
Hi @chasebolt !

I'm using 1.0.43 release, I should retest with 1.0.44 release to see if it's fixed.

**Comment by chasebolt** [comment]
took a closer look and the latest commit on master should address all of these issues. they have made their way into a release yet though.

**Comment by chasebolt** [comment]
after running some tests i noticed bullet 2 was still an issue. PR #477 should take care of this for you.

**Comment by drazzib** [comment]
I've just tested your PR #477 branch which seems to address my issues.
Thanks !

**Comment by chasebolt** [comment]
:+1:
