### ISSUE TITLE
No resource or method named `shell_out'

### ISSUE THREAD

**Issue by schu** [bflad/chef-docker#479]
```
No resource or method named `shell_out' for `Chef::Provider::DockerService::Upstart ""'
```

With the latest versions (>v1.0.40) this is a problem again.

Old issue: #353

**Comment by chasebolt** [comment]
What version of chef are you using?

**Comment by schu** [comment]
11.18.12 (with `no_lazy_load` set to `true`). So strictly speaking an unsupported version, but working until 68fe993bdd3fc61d3a2c654ea9af07231ede609f

**Comment by someara** [comment]
This cookbook only supports Chef 12. Please upgrade your chef-client version.
