### ISSUE TITLE
notifies :restart, "docker_container[...]" doesn't seem to work

### ISSUE THREAD

**Issue by cap10morgan** [bflad/chef-docker#50]
I added a restart notification to the template resource that creates a config file one of my containers relies on. The whole template & docker_container resources look like this:

```ruby
docker_container 'registry' do
  detach true
  port '5000:5000'
  env ['SETTINGS_FLAVOR=prod']
  volume ['/mnt/docker-registry-storage:/tmp/registry', '/mnt/docker-registry-config:/docker-registry/config']
end

template "/mnt/docker-registry-config/config.yml" do
  owner "root"
  group "docker"
  mode "664"
  action :create
  source "docker-registry-config.yml.erb"
  variables :config => {
              :loglevel     => "debug",
              :storage      => "local",
              :storage_path => "/tmp/registry",
              :secret_key   => Chef::EncryptedDataBagItem.load("secrets", "docker_registry")["secret_key"]
            }
  notifies :restart, "docker_container[registry]" # <--- what I added
end
```

After updating the template, I saw
```
Recipe: base::docker
  * docker_container[registry] action restart
```
in the Chef output, but the changes didn't take effect until I manually stopped and re-ran the registry container.

**Comment by muikrad** [comment]
I have the same problem. When I use a notifies :restart on a container, the container ends up in Exit (137) state and isn't restarted. When using stop followed by start though, it works.

**Comment by gionn** [comment]
:restart with upstart is borked, but maybe I've a fix.

**Comment by gionn** [comment]
If you want to try PR and test, just copy the template of the referenced PR in your cookbook (where you use docker_container resources), in templates/ and then use something like:

```
docker_container 'mycontainer' do
    init_template 'docker-container.conf.erb'
    cookbook 'yourcookbook'
end
```
