### ISSUE TITLE
docker_image action pull_if_missing when image already exists => LocalJumpError 

### ISSUE THREAD

**Issue by jperville** [bflad/chef-docker#501]
In the same spirit as #500, I get the same LocalJumpError when convering `docker_image action :pull_if_missing` and the image already exists. I am using version 2.0.0 of this cookbook with chef 12.4.3 (amd64) on ubuntu 14.04.

```         ================================================================================
             Error executing action `pull_if_missing` on resource 'docker_image[10.0.2.2:2000/busybox]'
             ================================================================================
             
             LocalJumpError
             --------------
             unexpected return
             
             Cookbook Trace:
             ---------------
             /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_image.rb:63:in `block in <class:DockerImage>'
             
             Resource Declaration:
       
             # In /tmp/vagrant-cache/chef/cookbooks/pm-docker/providers/data.rb
             
       38:   docker_image helper.image_name do
       39:     tag helper.image_tag
       40:     action :pull_if_missing # <-- never attempt to update once first pull
       41:   end
       42: end
             
             Compiled Resource:
             ------------------
       # Declared in /tmp/vagrant-cache/chef/cookbooks/pm-docker/providers/data.rb:38:in `pull_image'
             
             docker_image("10.0.2.2:2000/busybox") do
        action [:pull_if_missing]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_image
        cookbook_name "pm_docker_test"
        tag "ubuntu-14.04"
        repo "10.0.2.2:2000/busybox"
        connection #<Docker::Connection:0x00000007da77b0 @url="unix:///", @options={:socket=>"/var/run/docker.sock"}>
             end
```

**Comment by chasebolt** [comment]
Upgrading to chef-client 12.5.1 fixes this, if that is an option for you. 

@jkeiser this is the issue we ran into yesterday.

**Comment by chasebolt** [comment]
Some notes here. compat_resource does not like when an action returns nil, though chef 12.5.1 does not care and will continue on.

https://github.com/bflad/chef-docker/blob/master/libraries/docker_image.rb#L55
^^ if this conditional returns true, then return is nil and compat_resource gives the LocalJumpError.

**Comment by someara** [comment]
Fixed in 2.0.2

**Comment by jperville** [comment]
Thanks @someara and @chasebolt for quickly fixing this issue, which was a blocker. Upgrading to chef 12.5 is not an option for me yet, because I have one LWRP using `recipe_eval_with_update_check`, method which seems to have disappeared without notice sometimes between chef 12.4 and chef 12.5 (I'm interested in a workaround).

**Comment by someara** [comment]
paging @jkeiser re: recipe_eval_with_update_check

**Comment by jperville** [comment]
I just opened chef/chef#4053 to report the issue.
