### ISSUE TITLE
Socket permissions set to root:root, should be root:docker

### ISSUE THREAD

**Issue by agarat** [bflad/chef-docker#518]
The default installation of Docker sets the permissions for /var/run/docker.sock to root:docker. Using the chef-docker cookbook the permissions are set to root:root. 
Is this on purpose or am I missing something here?

**Comment by chasebolt** [comment]
specifying action :create on the docker_service downloads the docker binary and sets perm to root:root. this cookbook does not create a docker user so it can not set it to root:docker.

**Comment by someara** [comment]
The group property on the docker_service resource is here for this purpose.

https://github.com/bflad/chef-docker/blob/b9d6937a80fb220c873d73038acbf865aed67a59/libraries/docker_service.rb#L29

It is consumed here, and is rendered into the command opts that the docker daemon is started with.

https://github.com/bflad/chef-docker/blob/b9d6937a80fb220c873d73038acbf865aed67a59/libraries/helpers_service.rb#L163

```
group 'notroot'

docker_service 'default' do
  group 'notroot'
end
```
