### ISSUE TITLE
Consider switching to docker api for LWPR implementations

### ISSUE THREAD

**Issue by jcrobak** [bflad/chef-docker#76]
I've found that several edge cases in the current LWRPs are caused by failures in parsing or handling the output from `docker` shell commands. Docker has a REST API, which should be much more reliable for communicating without issue. There's even a ruby client implementing the api: https://github.com/swipely/docker-api

The major drawback of such an approach, AFAIK, is that the docker api sometimes makes breaking changes. We might have to handle various versions of docker differently (although hopefully this is stabilizing as we're approaching docker 1.0)

**Comment by someara** [comment]
Done!
